# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'SDWebImage', '~>3.7'
pod 'SnapKit', '~> 0.15.0'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MJExtension'
pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'

pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD', '~> 2.0.2'

pod 'Alamofire', '~> 3.0.0'
target '通讯录' do

end

target '通讯录UITests' do

end

